### ISSUE TITLE
Слово "приближенных" должно быть unsafe.

### ISSUE THREAD

**Issue by vladimir-vg** [hcodes/eyo#11]
"В условиях приближенных к реальным", https://ru.wiktionary.org/wiki/%D0%BF%D1%80%D0%B8%D0%B1%D0%BB%D0%B8%D0%B6%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9 ударение на и

"В кругу приближённых государя", https://ru.wiktionary.org/wiki/%D0%BF%D1%80%D0%B8%D0%B1%D0%BB%D0%B8%D0%B6%D1%91%D0%BD%D0%BD%D1%8B%D0%B9

Это два разных слова.

https://vk.com/wall475146_29886

**Comment by hcodes** [comment]
Спасибо, [поправил](https://github.com/hcodes/eyo-kernel/releases/tag/v1.0.5).
