### ISSUE TITLE
Словарь

### ISSUE THREAD

**Issue by sashasushko** [hcodes/eyo#12]
А по какому словарю или принципу, находятся слова с «ё»?  К примеру, у меня ё-фикатор пропустил «сойдёт». Куда добавлять или писать об ошибках и пропусках? У меня много текстов, на которых могу обкатать утилиту.

**Comment by hcodes** [comment]
Можно здесь заводить issue.
[Словарь безопасных слов](https://github.com/hcodes/eyo-kernel/blob/master/lib/eyo_safe.json)
Странно, но в словаре есть слово «сойдёт».
Нужен пример предложения.

**Comment by hcodes** [comment]
Может быть, у слова «сойдёт» первая буква «c» — латинская.

**Comment by sashasushko** [comment]
Это субтитры. 

> 490
> 00:57:10,779 --> 00:57:13,779
> Нужно ещё одно фото.
> Это не очень.
> 
> 491
> 00:57:14,099 --> 00:57:17,619
> Хватит.
> Это сойдет.

Возможно формат повлиял. Потому что отдельно действительно проходит. Завтра протестирую подробнее.

**Comment by hcodes** [comment]
Прогнал данный текст в `eyo`, «е» заменилась на «ё».

**Comment by sashasushko** [comment]
Да, проблема конкретно в написании слова в файле. Не уверен, что это общая проблема. Можно закрыть ишью. На всякий случай — вот кусок файла с злополучным словом:
[subtitles.txt](https://github.com/hcodes/eyo/files/511697/subtitles.txt)

**Comment by hcodes** [comment]
Всё-таки это баг, связанный с переносом строки.

**Comment by hcodes** [comment]
[Исправил](https://github.com/hcodes/eyo-kernel/releases/tag/v1.0.6).
