### ISSUE TITLE
Ёфикация не UTF-8 файлов

### ISSUE THREAD

**Issue by dima74** [hcodes/eyo#13]
Было бы здорово, если бы скрипт позволял ёфицировать не UTF-8 файлы, например файл локализации Chrome'а (у меня лежит по пути `/opt/google/chrome/locales/ru.pak`).

**Comment by hcodes** [comment]
Нужно распаковать `ru.pak`, прогнать тексты через `eyo` и обратно запаковать.

**Comment by dima74** [comment]
В принципе хорошее предложение, но насколько я понял это файл внутреннего Chromium'умовского формата, так что простого способа распаковать нету.

**Comment by hcodes** [comment]
Специфический формат, тащить его в `eyo` не хочется.

**Comment by dima74** [comment]
В принципе да, тут вы правы.
