### ISSUE TITLE
in-place ёфикация 

### ISSUE THREAD

**Issue by dima74** [hcodes/eyo#15]
Добавьте, пожалуйста, опцию для ёфикации файла «на месте» (как при выполнение команд `eyo file >temp && mv temp file`)

**Comment by hcodes** [comment]
Так устроит `eyo file -o file`?

**Comment by dima74** [comment]
Может всё-таки `eyo --in-place file`?)

**Comment by Kristinita** [comment]
+1

**Comment by hcodes** [comment]
v4.2.0
`eyo -i README.md`
