### ISSUE TITLE
Поддержка нескольких файлов

### ISSUE THREAD

**Issue by lex111** [hcodes/eyo#21]
@hcodes привет, спасибо за крутой инструмент!

Интересует, будет ли поддержка проставление буквы "ё" для нескольких файлов, допустим, у меня есть книга, она состоит из 10 файлов в формате Markdown, и я хочу во  всех них провести ёфикацию.

Как вариант, сделать автоматическую замену, указав список файлов по маске (`*.md`), примерно так:

```sh
$ eyo "*.md"
```

По аналогии c `yaspeller "*.md"`

И всё, потом по через систему контроля версий можно проверить корректность замены, например.

Планируется ли подобное?

**Comment by hcodes** [comment]
Удобно, надо сделать.

**Comment by Kristinita** [comment]
+1. Желательно, чтобы это поддерживалось как в Windows, так и в *NIX. Например, npm glob [**поддерживает Windows**](https://www.npmjs.com/package/glob#windows).

Спасибо.

**Comment by hcodes** [comment]
v4.2.0
`eyo -i "*.md"`
