### ISSUE TITLE
feature_request(enhancement): показ в консоли только Safe replacements

### ISSUE THREAD

**Issue by Kristinita** [hcodes/eyo#22]
### 1. Запрос

Неплохо было бы, если б была возможность показывать в консоли только `Safe replacements`.

![Safe replacements](https://raw.githubusercontent.com/hcodes/eyo/master/images/screenshot.png)

### 2. Аргументация

Чтобы не загромождать консольный вывод.

Положим, имеется [**большой набор файлов**](https://github.com/Kristinita/Erics-Green-Room), где требуется проверить ёфицированность. Да, пока поддержка множества файлов [**не поддерживается**](https://github.com/hcodes/eyo/issues/21), но можно и написать скрипты. Пользователь проверил файлы → заменил, что требуется, добавил eyo в список задач для непрерывной интеграции в Travis CI и/или AppVeyor.

`Not safe replacements` для каждого из множества файлов будет загромождать консольный вывод и мешать пользователю видеть как `Safe replacements` от eyo, так и полезные сообщения от других программ, включённых в непрерывную интеграцию.

### 3. Пример реализации

Если пользователь введёт команду:

    eyo --lint --safe SashaFile.txt

В консоли будут показаны только `Safe replacements`, но не `Not safe replacements`.

Спасибо.

**Comment by hcodes** [comment]
v4.1.0
Параметр `--only-safe`.

**Comment by Kristinita** [comment]
**Status: :heavy_check_mark: Работает для меня**

Спасибо.
