### ISSUE TITLE
bug(base): safe replacements errors

### ISSUE THREAD

**Issue by Kristinita** [hcodes/eyo#24]
### 1. Summary

В списке ниже собрал все, по моему мнению, ошибочные случаи safe replacements, которые возникли, когда попробовал применить eyo к своим текстам. Считаю, что все случаи необходимо перенести из `safe replacements` в `not safe replacements`.

### 2. Примечания к списку

1. Если у меня в списке стоит заглавная `Е`, это означает, что eyo в этом месте произвёл замену `е` на `ё`. Например, если в списке `ЧЕс`, это значит, что eyo заменил `Чес` на `Чёс`.
1. Если для имён нарицательных источник не указан, то это [**Иванова О. Е., Лопатин В. В. Русский орфографический словарь - Москва, 2004 г.**](http://orf.textologia.ru/); в остальных случаях для имён нарицательных источник прямо указывается.
1. Для иноязычных имён собственных (Утер Пендрагон, Ирма Грезе и т. д.) мне не удалось найти специализированных орфографических словарей, показывающих, пишутся ли эти имена собственные через `е` или `ё`. При невозможности найти специализированные источники, однако, мне кажется достаточным дать ссылку на употребление рассматриваемого имени собственного в авторитетных источниках, чтобы подтвердить правоту или допустимость написания через `е`.

### 3. Список

1. [**суперзвЕзды&#x301;**](http://orf.textologia.ru/definit/superzvezda/?q=532&n=139760) — родительный падеж существительного `суперзвезда`;
1. [**лЕвко&#x301;й**](http://orf.textologia.ru/definit/levkoy/?q=532&n=58215) — [**травянистое растение**](https://dic.academic.ru/searchall.php?SWord=%D0%BB%D0%B5%D0%B2%D0%BA%D0%BE%D0%B9&from=xx&to=ru);
1. [**УтЕр Пендрагон**](https://dic.academic.ru/searchall.php?SWord=%D0%A3%D1%82%D0%B5%D1%80+%D0%9F%D0%B5%D0%BD%D0%B4%D1%80%D0%B0%D0%B3%D0%BE%D0%BD&from=xx&to=ru&did=&stype=0) — отец короля Артура;
1. [**Ки&#x301;Ев**](http://orf.textologia.ru/definit/kiev/?q=532&n=50293) — столица Украины;
1. [**ступнЕ&#x301;й**](http://orf.textologia.ru/definit/stupnya/?q=532&n=139156) — родительный падеж множественного числа слова `ступня`;
1. [**СилЕн**](https://dic.academic.ru/searchall.php?SWord=%D0%A1%D0%B8%D0%BB%D0%B5%D0%BD&from=xx&to=ru&did=&stype=0) — сатир, персонаж древнегреческой мифологии;
1. [**ЧЕс Чендлер**](https://kristinita.ru/#gsc.tab=0&gsc.q=%D0%A7%D0%B5%D1%81%20%D0%A7%D0%B5%D0%BD%D0%B4%D0%BB%D0%B5%D1%80) — менеджер Джими Хендрикса;
1. [**берЕзозол**](https://dic.academic.ru/dic.nsf/vasmer/36795/%D0%B1%D0%B5%D1%80%D0%B5%D0%B7%D0%BE%D0%B7%D0%BE%D0%BB) — древнерусское название апреля; (источник — этимологический словарь Макса Фасмера);
1. [**БерЕзники&#x301;**](http://gramota.ru/slovari/dic/?word=%D0%91%D0%B5%D1%80%D0%B5%D0%B7%D0%BD%D0%B8%D0%BA%D0%B8&all=x) — город Пермского края (источник — [**словарь имён собственных русского языка Ф. Л. Агеенко**](http://gramota.ru/slovari/info/ag/));
1. [**Бас-ТЕр**](http://gramota.ru/slovari/dic/?lop=x&bts=x&ro=x&zar=x&ag=x&ab=x&sin=x&lv=x&az=x&pe=x&word=%D0%91%D0%B0%D1%81-%D0%A2%D0%B5%D1%80) — [**административный центр Гваделупы**](https://bigenc.ru/geography/text/2346462) (источник — тот же словарь имён собственных);
1. [**Уильям ИстЕрли**](https://kristinita.ru/#gsc.tab=0&gsc.q=%D0%A3%D0%B8%D0%BB%D1%8C%D1%8F%D0%BC%20%D0%98%D1%81%D1%82%D0%B5%D1%80%D0%BB%D0%B8) — экономист;
1. [**живЕ&#x301;те**](http://orf.textologia.ru/definit/zhivete/?q=532&n=35464) — буква кириллицы;
1. [**твЕ&#x301;рдо**](http://orf.textologia.ru/definit/tverdo/?q=532&n=141626) — буква кириллицы;
1. [**Ирма ГрЕзе**](https://kristinita.ru/#gsc.tab=0&gsc.q=%D0%B3%D1%80%D0%B5%D0%B7%D0%B5%20%D0%B8%D1%80%D0%BC%D0%B0) — надзирательница концлагерей, известная своей жестокостью;
1. [**Ричард СпЕк**](https://kristinita.ru/#gsc.tab=0&gsc.q=%D0%A0%D0%B8%D1%87%D0%B0%D1%80%D0%B4%20%D0%A1%D0%BF%D0%B5%D0%BA) — серийный убийца;
1. [**БЕлль Ганнесс**](https://kristinita.ru/#gsc.tab=0&gsc.q=%D0%91%D0%B5%D0%BB%D0%BB%D1%8C%20%D0%93%D0%B0%D0%BD%D0%BD%D0%B5%D1%81%D1%81) — женщина — серийный убийца;
1. [**разли&#x301;чЕн**](https://dic.academic.ru/dic.nsf/dic_forms/60380/%D1%80%D0%B0%D0%B7%D0%BB%D0%B8%D1%87%D0%BD%D1%8B%D0%B9) — причастие от `различный` (источник — Полная акцентуированная парадигма по А. А. Зализняку).

---

Если с чем-то не согласны, пожалуйста, сообщите.

Спасибо.

**Comment by Kristinita** [comment]
@hcodes , актуально. Пожалуйста, проверьте список выше.

Спасибо.

**Comment by hcodes** [comment]
Со всем согласен, нужно поправить.

**Comment by hcodes** [comment]
Спасибо за помощь, всё поправил.
v4.1.1

**Comment by Kristinita** [comment]
Новые замеченные неточности. Примечания те же, что и в первом сообщении данного issue. Протестировано на eyo 4.2.0.

1. [**протЕ&#x301;кший**](https://dic.academic.ru/dic.nsf/ushakov/988054) — толковый словарь Ушакова допускает написание через «е»;
1. [**недрЕма&#x301;нное око**](http://orf.textologia.ru/definit/nedremannoe-oko/?q=532&n=74728) — см. [**комментарии**](https://common_mistakes.academic.ru/226/%D0%BD%D0%B5%D0%B4%D1%80%D0%B5%D0%BC%D0%B0%D0%BD%D0%BD%D1%8B%D0%B9) в «Словаре ошибок русского языка» Григория Александровича Крылова;
1. [**поко&#x301;шЕн**](http://orf.textologia.ru/definit/pokoshenniy/?q=532&n=93155) — краткая форма слова «покошенный»;
1. [**замЕ&#x301;т**](https://dic.academic.ru/dic.nsf/mas/16180/%D0%B7%D0%B0%D0%BC%D0%B5%CC%81%D1%82%D0%B0) — родительный падеж от «замета» — «отметка, знак». Источник — Малый академический словарь Института русского языка Академии наук СССР.
1. [**Прочь буйна чернь, непросвещЕ&#x301;нна**](https://rvb.ru/18vek/derzhavin/01text/098.htm) — «е» в контексте стихотворения Державина «О удовольствии»;
1. [**Ничтожный призрак, иль ещЕ&#x301; Москвич в Гарольдовом плаще**](http://pushkin-lit.ru/pushkin/text/evgenij-onegin/onegin_7.htm) — в данном контексте из «Евгения Онегина» «еще», см. **#26**;
1. [**киЕм**](https://yo_use.academic.ru/3168/%D0%BA%D0%B8%D0%B5%D0%BC) — форма с «е» допустима в «Словаре употребления буквы Ё» Чумакова, о котором говорилось в **#27**;
1. [**клешнЕ&#x301;й**](http://orf.textologia.ru/definit/kleshnya/?q=532&n=51194) — родительный падеж множественного числа существительного «клешня»;
1. Костер — «е» в контексте [**Шарль де КостЕ&#x301;р**](https://dic.academic.ru/dic.nsf/es/18231/%D0%94%D0%95) — автор «Легенды об Уленшпигеле…» — и [**Николай КостЕр-Вальдау**](https://www.vokrug.tv/person/show/nikolaj_coster-waldau/) — актёр «Игры Престолов»;
1. [**ЗуЕв**](http://imja.name/familii/zuev.shtml) — фамилия; источники — Веселовский С. Б. Ономастикон. Древнерусские имена, прозвища и фамилии. М., 1974; Словарь русских народных говоров. Вып. 12. Л., 1977; Суперанская А. В. Современный словарь русских личных имен. М., 2005; Тупиков Н. М. Словарь древнерусских личных собственных имен. М., 2004.
1. [**Гуань МоЕ**](https://www.svoboda.org/a/24736430.html) — настоящее имя писателя Мо Яня, в данном контексте «Мое»;
1. Никола [**ТЕ&#x301;сла**](https://dic.academic.ru/dic.nsf/bse/171240/%D0%A2%D0%B5%D1%81%D0%BB%D0%B0) — инженер и изобретатель;
1. [**пересЕ&#x301;кший**](http://orf.textologia.ru/definit/peresekshiy/?q=532&n=105270) — допустимая форма;
1. [**прет-а-портЕ&#x301;**](http://orf.textologia.ru/definit/pret-a-porte/?q=532&n=114070) — в данном слове с дефисами «прет», а не «прёт»;
1. [**хай-тЕ&#x301;к**](http://orf.textologia.ru/definit/hay-tek/?q=532&n=153315) — в данном слове с дефисом «тек», а не «тёк»;
1. [**шрЕ&#x301;дер**](http://orf.textologia.ru/definit/shreder/?q=532&n=159536).

Спасибо.

**Comment by hcodes** [comment]
Эти замечания нужно в новую задачу перенести, иначе они потеряются.

**Comment by hcodes** [comment]
https://github.com/hcodes/eyo/issues/29

**Comment by Kristinita** [comment]
Считаю, нужно переоткрыть issue, поскольку не всё из первого поста исправлено. Если изменения не были добавлены не случайно, а по какой-либо аргументации, лучше это обсудить.

### 1. Данные

+ `KiraEyo.md`:

```makrdown
+ Бас-Тер
+ из Березников
+ Утер Пендрагон
+ Чес Чендлер
```

### 2. Шаги для воспроизведения

	eyo --lint --only-safe KiraEyo.md

### 3. Желаемое поведение

Нет `Safe replacements`.

### 4. Актуальное поведение

```node
[ERR] test.md
Safe replacements:
1. Тер → Тёр (1:7)
2. Березников → Берёзников (2:6)
3. Утер → Утёр (3:3)
4. Чес → Чёс (4:3)
```

### 5. Примечание

1. [**Архангельский областной словарь**](http://www.philol.msu.ru/~dialectology/dictionary/aos2.pdf#page=5) под редакцией [**кандидата филологических наук, доцента**](http://www.ruslang.ru/doc/dialectolog/moskva.pdf) Оксаны Гецовой; и [**Новый толково-образовательный словарь русского языка**](https://slovar.cc/rus/efremova-slovo/1078786.html) Татьяны Ефремовой допускают обе формы: «березник» и «берёзник». Поэтому, полагаю, данный пример подлежит исключению из словарей eyo.

### 6. Программное обеспечение

+ Node.js 12.1.0
+ eyo 4.2.0

Спасибо.
