### ISSUE TITLE
core-метод

### ISSUE THREAD

**Issue by iamstarkov** [hcodes/eyo#6]
привет, спасибо за ёфикатор. хотел спросить не было ли мысли разделить cli и сам метод ёфикации, который принимает строку и возвращает строку?

**Comment by hcodes** [comment]
Да, нужно разделить на два пакета kernel и cli.
У kernel будут минимальные зависимости.

**Comment by iamstarkov** [comment]
👍

**Comment by hcodes** [comment]
https://github.com/hcodes/eyo-kernel

**Comment by iamstarkov** [comment]
крутотень
